name: Generate Snake
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        owner: ['Ohto-Ai', 'beiklive']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ matrix.owner }}
          gif_out_path: ./assets/github-contribution-grid-snake-${{ matrix.owner }}.gif
          svg_out_path: ./assets/github-contribution-grid-snake-${{ matrix.owner }}.svg
      - name: Push to GitHub
        run: |
          git commit -a -m "Generate Contribution Snake for ${{ matrix.owner }}"
          git pull --rebase
          git push --force
